name: Build and Package for Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10  # Replace with your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies if needed

    - name: Build for Windows
      run: |
        pyinstaller --noconsole --onefile main.py

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-exe
        path: dist/main.exe  # Replace with your actual path
